FROM resin/raspberry-pi-node:6.10-slim 
ENTRYPOINT []

RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

ADD ./build /app/build
ADD ./node_modules /app/node_modules
# RUN npm install -g create-react-app
# RUN npm install -g serve
# RUN npm -v
# RUN npm install --production

# ADD ./src /app/src
ADD ./app.js /app

# RUN npm build

EXPOSE 5000

CMD [ "node", "app.js" ]